### ISSUE TITLE
Merging our efforts

### ISSUE THREAD

**Issue by 197g** [jrsala/Peano#1]
I have recently delved into the same topic as this project and written some functional templates on my own, although it has a few conceptional differences.
https://github.com/HeroicKatora/Functional-Cpp-Templates

My own contributions to the topic are specifically using c++17 features to, for example, allow converting all the typename templates in the c++ standard to functions inside functional template language, providing a way for matching, and Lambda-like function definitions.

Now I do not know whether or not you are interested, but I would really enjoy seeing you join the effort :)

If you would, feel free to join the Discord server https://discord.gg/jAyP79x

**Comment by jrsala** [comment]
Oh hey, thanks a lot for the interest! And sorry for not answering earlier, I'm not very active on GitHub as you may have seen.

I only see this kind of template programming (my Peano arithmetic project) as a fun curiosity, and I see your headerlib as a valiant attempt to make C++ nicer than it was designed to be, but I think you can't make it as nice as you would like to. I don't want to discourage you because efforts such as yours can definitely turn out to bring a lot of value to people and to the industry, but I think the solution to the problem of easy and convenient programming in the template language is to create a new, better language than C++.

Keep it up, though! Here's my star
